# Parameters for the LoveIt theme.

# LoveIt theme version
version = "0.2.x"
themesDir = "../.."

# public git repo url only then enableGitInfo is true
gitRepo = "https://github.com/SmilyBorg/unakarlsen.com"

# site default theme ("light", "dark", "auto")
defaultTheme = "dark"

[header]
  # desktop header mode ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  mobileMode = "auto"
  [header.title]
    # URL of the LOGO
    logo = ""
    # title name
    name = "Una Karlsen"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # whether to use typeit animation for title name
    typeit = false

[footer]
  enable = true
  # Custom content (HTML format is supported)
  custom = ''
  # whether to show Hugo and theme info
  hugo = true
  # whether to show copyright info
  copyright = true
  # whether to show the author
  author = true
  # Site creation time
  since = 2020
  # license info (HTML format is allowed)
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Section (all posts) page config
[params.section]
  # special amount of posts in each section page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

# List (category or tag) page config
[params.list]
  # special amount of posts in each list page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

# Home Page Info
[home]
  # Home Page Profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = "una@unakarlsen.com"
    # title shown in home page (HTML format is supported)
    title = ""
    # subtitle shown in home page
    subtitle = "Creative · Maker · Cinematographer · Photographer"
    # whether to use typeit animation for subtitle
    typeit = false
    # whether to show social links
    social = true
    # disclaimer (HTML format is supported)
    disclaimer = ""

  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6

# Social Info in home page
[social]
  GitHub = "SmilyBorg"
  Twitter = "SmilyBorg"
  Instagram = "unakarlsen"
  Facebook = "UnaKarlsenCreator"
  Youtubelegacy = "UnaAlexiaKarlsen"
  Twitch = "unakarlsen"
  Email = "una@unakarlsen.com"
  Keybase = "SmilyBorg"
  Pinterest = "SmilyBorg"
  Paypal = "unakarlsen"
  Goodreads = "10006011-una"
  Kickstarter = "SmilyBorg"
  Patreon = "SmilyBorg"
  Steam = "SmilyBorg"
  Thingiverse = "SmilyBorg"
  Vimeo = "SmilyBorg"
  LinkedIn="unakarlsen"
  
  # Gitlab = "SmilyBorg"
  
  # Soundcloud = "SmilyBorg"
  # Medium = "@SmilyBorg"
  # Lastfm = "SmilyBorg"
  # Wordpress = "SmilyBorg"
  
  # Telegram = "xxxx"
  # Youtubecustom = "xxxx"
  # Youtubechannel = "xxxx"
  # Tumblr ="xxxx"
  # Quora = "xxxx"
  # Reddit = "SmilyBorg"
  # Codepen = "xxxx"
  # FreeCodeCamp = "xxxx"
  # Bitbucket = "xxxx"
  # Stackoverflow = "xxxx"
  # Weibo = "xxxx"
  # Odnoklassniki = "xxxx"
  # VK = "xxxx"
  # Flickr = "xxxx"
  # Xing = "xxxx"
  # Snapchat = "xxxx"
  # Spotify = "xxxx"
  # Bandcamp = "xxxx"
  # Fivehundredpx = "xxxx"
  # Mix = "xxxx"
  # Foursquare = "xxxx"
  # Hackernews = "xxxx"
  # Twitch = "xxxx"
  # Strava = "xxxx"
  # Skype = "xxxx"
  # Whatsapp = "xxxx"
  # Zhihu = "xxxx"
  # Douban = "xxxx"
  # Angellist = "xxxx"
  # Slidershare = "xxxx"
  # Jsfiddle = "xxxx"
  # Deviantart = "xxxx"
  # Behance = "xxxx"
  # Dribble = "xxxx"
  # Vine = "xxxx"
  # Googlescholar = "xxxx"
  # Researchgate = "xxxx"

  # Devto = "xxxx"
  # Gitea = "xxxx"
  # XMPP = "xxxx"
  # Matrix = "xxxx"
  # Bilibili = "xxxx"

  [social.Mastodon]
    id = "@Unakarlsen"
    Prefix = "https://mastodon.online/"


# Social Share Links in post page
[share]
  enable = false
  Twitter = true
  Facebook = true
  
[params.page.comment]
  enable = true
  # Disqus comment config (https://disqus.com/)
  [params.page.comment.disqus]
    enable = false
    # Disqus shortname to use Disqus in posts
    shortname = ""
    # Gitalk comment config (https://github.com/gitalk/gitalk)
  [params.page.comment.gitalk]
    enable = false
    owner = ""
    repo = ""
    clientId = ""
    clientSecret = ""

[math]
  enable = true
  # default block delimiter is $$ ... $$ and \\[ ... \\]
  blockLeftDelimiter = ""
  blockRightDelimiter = ""
  # default inline delimiter is $ ... $ and \\( ... \\)
  inlineLeftDelimiter = ""
  inlineRightDelimiter = ""
  # KaTeX extension copy_tex
  copyTex = true
  # KaTeX extension mhchem
  mhchem = true


# site verification code for Google/Bing/Yandex/Pinterest/Baidu
[verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""

 # Analytics config
 [analytics]
  enable = false
  # Google Analytics
  [analytics.google]
    id = ""
    # whether to anonymize IP
    anonymizeIP = true
  # Fathom Analytics
  [analytics.fathom]
    id = ""
    # server url for your tracker if you're self hosting
    server = ""

  # Cookie consent config
  [cookieconsent]
    enable = false
    # text strings used for Cookie consent banner
    [cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

# Publisher Info just for SEO
[publisher]
  name = "xxxx"
  [publisher.logo]
    url = "logo.png"
    width = 127
    height = 40

# Website Log Info just for SEO
[logo]
  url = "logo.png"
  width = 127
  height = 40

# Website Image Info just for SEO
[image]
  url = "cover.png"
  width = 800
  height = 600