# Parameters for the LoveIt theme.

# LoveIt theme version
version = "0.2.X"
# public git repo url only then enableGitInfo is true
gitRepo = "https://github.com/SmilyBorg/unakarlsen.com"

# site default theme ("light", "dark", "auto")
defaultTheme = "dark"

[header]
  # desktop header mode ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  mobileMode = "auto"

[footer]
  # Site creation time
  since = 2020
  # license info (HTML format is allowed)
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Home Page Info
[home]
  # Home Page Profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = "una@unakarlsen.com"
    # subtitle shown in home page
    subtitle = "Tech 路 Tools 路 Cameras 路 Chronic-Illness 路 Life"
    # whether to use typeit animation for subtitle
    typeit = false
    # whether to show social links
    social = true

# Social Info in home page
[social]
  GitHub = "SmilyBorg"
  Twitter = "SmilyBorg"
  Instagram = "unakarlsen"
  Facebook = "UnaKarlsenCreator"
  Youtubelegacy = "UnaAlexiaKarlsen"
  #Twitch = "unakarlsen"
  Email = "una@unakarlsen.com"
  Keybase = "SmilyBorg"
  #Pinterest = "SmilyBorg"
  #Paypal = "unakarlsen"
  Goodreads = "10006011-una"
  #Kickstarter = "SmilyBorg"
  #Patreon = "SmilyBorg"
  Steam = "SmilyBorg"
  #Thingiverse = "SmilyBorg"
  #Vimeo = "SmilyBorg"
  #LinkedIn = "unakarlsen"
  Discord = "LexiOfBorg#7144"
  Mastodon = "UnaKarlsen"
  MastodonPrefix = "https://mastodon.online/"

  #[social.DockerHub]
  #  # weight when arranging icons (the greater the weight, the later the icon is positioned)
  #  weight = 10
  #  # your social ID
  #  id = "smilyborg"
  #  # prefix of your social link
  #  prefix = "https://hub.docker.com/u/"
  #  # content hovering on the icon
  #  title = "Docker Hub"
  #  [social.DockerHub.Icon]
  #    class= "fab fa-brands fa-docker fa-fw"

  [social.DiscordServer]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 10
    # your social ID
    id = "NMsD5yQ"
    # prefix of your social link
    prefix = "https://discord.com/invite/"
    # content hovering on the icon
    title = "Ko-fi"
    [social.DiscordServer.Icon]
      class= "fab fa-brands fa-discord fa-fw"  

  [social.Ko-fi]
    # weight when arranging icons (the greater the weight, the later the icon is positioned)
    weight = 10
    # your social ID
    id = "unakarlsencreator"
    # prefix of your social link
    prefix = "https://Ko-fi.com/"
    # content hovering on the icon
    title = "Ko-fi"
    [social.Ko-fi.Icon]
      src = "lib/simple-icons/icons/ko-fi.svg"

  # telegram
  # reddit
  # whatsapp
  # deviantart
  # udemy
  # bandcamp

  #Gitlab = "SmilyBorg"
  


  # Soundcloud = "SmilyBorg"
  # Medium = "@SmilyBorg"
  # Lastfm = "SmilyBorg"
  # Wordpress = "SmilyBorg"
  
  # Telegram = "xxxx"
  # Youtubecustom = "xxxx"
  # Youtubechannel = "xxxx"
  # Tumblr ="xxxx"
  # Quora = "xxxx"
  # Reddit = "SmilyBorg"
  # Codepen = "xxxx"
  # FreeCodeCamp = "xxxx"
  # Bitbucket = "xxxx"
  # Stackoverflow = "xxxx"
  # Weibo = "xxxx"
  # Odnoklassniki = "xxxx"
  # VK = "xxxx"
  # Flickr = "xxxx"
  # Xing = "xxxx"
  # Snapchat = "xxxx"
  # Spotify = "xxxx"
  # Bandcamp = "xxxx"
  # Fivehundredpx = "xxxx"
  # Mix = "xxxx"
  # Foursquare = "xxxx"
  # Hackernews = "xxxx"
  # Twitch = "xxxx"
  # Strava = "xxxx"
  # Skype = "xxxx"
  # Whatsapp = "xxxx"
  # Zhihu = "xxxx"
  # Douban = "xxxx"
  # Angellist = "xxxx"
  # Slidershare = "xxxx"
  # Jsfiddle = "xxxx"
  # Deviantart = "xxxx"
  # Behance = "xxxx"
  # Dribble = "xxxx"
  # Vine = "xxxx"
  # Googlescholar = "xxxx"
  # Researchgate = "xxxx"
  # Mastodon = "xxxx"
  # MastodonPrefix = "https://mastodon.technology/"
  # Devto = "xxxx"
  # Gitea = "xxxx"
  # XMPP = "xxxx"
  # Matrix = "xxxx"
  # Bilibili = "xxxx"
# Social Share Links in post page
[share]
  enable = true
  Twitter = true
  Facebook = true
  Linkedin = true
  Pinterest = true

[math]
  enable = true
  # default block delimiter is $$ ... $$ and \\[ ... \\]
  blockLeftDelimiter = ""
  blockRightDelimiter = ""
  # default inline delimiter is $ ... $ and \\( ... \\)
  inlineLeftDelimiter = ""
  inlineRightDelimiter = ""
  # KaTeX extension copy_tex
  copyTex = true
  # KaTeX extension mhchem
  mhchem = true


# site verification code for Google/Bing/Yandex/Pinterest/Baidu
[params.verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""

# Publisher Info just for SEO
[params.publisher]
  name = "xxxx"
  [params.publisher.logo]
    url = "logo.png"
    width = 127
    height = 40

# Website Log Info just for SEO
[params.logo]
  url = "logo.png"
  width = 127
  height = 40

# Website Image Info just for SEO
[params.image]
  url = "cover.png"
  width = 800
  height = 600
